/*
 * displayInterface.c
 *
 *  Created on: 30 ago. 2019
 *      Author: Tomas
 */


#include "displayInterface.h"
#include "displayDriver.h"
#include "leds.h"
#include "SysTick.h"
#include "stdlib.h"
/*-------------------------------------------
 ----------------DEFINES---------------------
 -------------------------------------------*/
#define MARQUEE_BUFFER_SIZE		20

/*-------------------------------------------
 ----------------GLOBAL_VARIABLES------------
 -------------------------------------------*/
static char marquee_buffer[MARQUEE_BUFFER_SIZE];
static int marquee_buffer_curr_size = 0;
static direction_t marquee_curr_dir;
//static int marquee_curr_vel = 0;
static display_info_t info;
static inform_event_callback_t event_callback = NULL;
/*-------------------------------------------
 ---------STATIC_FUNCTION_DECLARATION--------
 -------------------------------------------*/
//callback that will be called with each sysTick call when marquee has been enabled.
static void marquee_callback();
//clears the marquee buffer.
static void clear_marquee_buffer();
//sets the marquee buffer with the sentence that should be marqueed.
static void set_marquee_buffer(char* sentence);
//sets the callback that should be called when a new event has been generated by display.
static void set_inform_event_callback(inform_event_callback_t callback);
//gets last not null character from marquee buffer
static char look_for_last_not_null();
//removes last not null character from marquee buffer
static void remove_last_not_null();
/*-------------------------------------------
 ----------FUNCTION_IMPLEMENTATION-----------
 -------------------------------------------*/

void init_display_interface(inform_event_callback_t callback){
	static bool initialized = false;

	info.number_of_pos = AMOUNT_MAX_DISPLAY_POS;
	if(initialized) return;
	leds_init();
	display_init();
	clear_marquee_buffer();
	set_inform_event_callback(callback);
	systick_init();
	systick_add_callback(marquee_callback, SYSTICK_ISR_FREQUENCY_HZ, PERIODIC);
	systick_disable_callback(marquee_callback);
	initialized = true;
}

void marquee(char* sentence, direction_t dir){
	//FALTA TEMA TIEMPOOOOS!!!
	clear_marquee_buffer();
	set_marquee_buffer(sentence);
	marquee_curr_dir = dir;
	//marquee_curr_vel = vel;
	//set vel for sysTick!!!
	systick_enable_callback(marquee_callback);
}

static void clear_marquee_buffer(){
	for(int i = 0; i < AMOUNT_MAX_DISPLAY_POS; i++)
		marquee_buffer[i] = NULL_CHAR;
}

static void set_marquee_buffer(char* sentence){
	int i = 0;
	for(; i < MARQUEE_BUFFER_SIZE; i++)
		if(sentence[i] != NULL_CHAR)
			marquee_buffer[i] = sentence[i];
		else
			break;

	marquee_buffer_curr_size = i;
}
static void marquee_callback(){
	static bool should_shift = false;
	static int chars_written = 0;
	static int finishing_shift_counter = 0;
	char aux = NULL_CHAR;

	if(!should_shift){
		if(marquee_curr_dir == LEFT)
			chars_written = write_sentence(marquee_buffer);
		else
			clear_all();
		should_shift = true;
	}
	else if((marquee_curr_dir == LEFT) && marquee_buffer[chars_written] != NULL_CHAR){
		shift(marquee_curr_dir, marquee_buffer[chars_written]);
		chars_written++;
	}
	else if((marquee_curr_dir == RIGHT) && ((aux = look_for_last_not_null()) != NULL_CHAR) ){
		remove_last_not_null();
		shift(marquee_curr_dir, aux);
	}
	else if(finishing_shift_counter < AMOUNT_MAX_DISPLAY_POS){
		shift(marquee_curr_dir, NULL_CHAR);
		finishing_shift_counter++;
	}
	else if(finishing_shift_counter == AMOUNT_MAX_DISPLAY_POS){
		finishing_shift_counter = 0;
		should_shift = false;
		chars_written = 0;
		display_event_t event;
		event.id = MARQUEE_FINISHED;
		event_callback(event);
		systick_disable_callback(marquee_callback);
	}
}

static void set_inform_event_callback(inform_event_callback_t callback){
	event_callback = callback;
}

void set_blinking_one(bool on_off, int pos){
	blink_one(pos, on_off);
}
bool get_is_blinking(int pos){
	return is_blinking_one(pos);
}
bool get_is_blinking_any(){
	bool blinking_any = false;
	for(int i = 0; i < AMOUNT_MAX_DISPLAY_POS; i++)
		if( (blinking_any = is_blinking_one(i)) )
			break;

	return blinking_any;
}
void set_blinking_all(bool on_off){
	for(int i = 0; i < AMOUNT_MAX_DISPLAY_POS; i++)
		blink_one(i, on_off);
}
void write_word_2_display(const char* word){
	write_sentence(word);
}
void write_char_2_display(char c, int pos){
	if(pos < AMOUNT_MAX_DISPLAY_POS)
		write_char(c, pos);
}
display_info_t get_display_info(){
	return info;
}
void clear_all(){
	display_clear_all();
}
static char look_for_last_not_null(){
	for(int i = MARQUEE_BUFFER_SIZE-1; i >=0; i--)
		if(marquee_buffer[i] != NULL_CHAR)
			return marquee_buffer[i];

	return NULL_CHAR;

}

static void remove_last_not_null(){
	for(int i = MARQUEE_BUFFER_SIZE-1; i >=0; i--)
			if(marquee_buffer[i] != NULL_CHAR){
				marquee_buffer[i] = NULL_CHAR;
				break;
			}
}
void clear_all_leds(){
	for(int i =0; i < AMOUNT_MAX_DIODES_POS; i++)
		write_led(i, false);
}
void write_to_led(int pos, bool on_off){
	write_led(pos, on_off);
}
void set_blinking_leds_all(bool on_off){
	for(int i =0; i < AMOUNT_MAX_DIODES_POS; i++)
		blink_led(i, on_off);
}
bool get_is_blinking_leds_any(){
	bool any = false;
	for(int i =0; i < AMOUNT_MAX_DIODES_POS; i++)
		if( (any = is_blinking_led_one(i)) )
			break;
	return any;
}
bool get_blinking_led_one(int pos){
	return is_blinking_led_one(pos);
}
void set_blinking_led_one(int pos, bool on_off){
	blink_led(pos, on_off);
}
void display_set_brightness_one_up_down(int pos, direction_t dir){
	if(dir == UP)
		display_set_brightness_one_pos(pos, display_get_brightness_one(pos) + 1);
	else if(dir == DOWN)
		display_set_brightness_one_pos(pos, display_get_brightness_one(pos) - 1);
}

void display_set_brightnes_led(int pos, int brightness){
	led_set_brightness_one(pos, brightness);
}
void display_set_brightness_leds(int brightness){
	for(int i =0; i < AMOUNT_MAX_DIODES_POS; i++)
		led_set_brightness_one(i, brightness);
}
void display_set_brightness_led_up_down(int pos, direction_t dir){
	if(dir == UP)
		led_set_brightness_one(pos, led_get_brightness_one(pos) + 1);
	else if(dir == DOWN)
		led_set_brightness_one(pos, led_get_brightness_one(pos) - 1);
}
void display_set_brightness_leds_up_down(direction_t dir){
	for (int i =0 ; i < AMOUNT_MAX_DIODES_POS; i++)
		display_set_brightness_led_up_down(i, dir);
}
void display_set_brightness_up_down(direction_t dir){

	for (int i =0 ; i < AMOUNT_MAX_DISPLAY_POS; i++)
		display_set_brightness_one_up_down(i,dir);

}
void display_set_brightness_one_pos(int pos, int brightness){
	display_set_brightness_one(pos, brightness);
}
